# Generated by Django 6.0 on 2025-12-08 23:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaProcessamento',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('STARTED', 'Iniciado'), ('SUCCESS', 'Sucesso'), ('FAILURE', 'Falha')], db_index=True, default='PENDING', max_length=20)),
                ('progresso', models.IntegerField(default=0)),
                ('log_erros', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
