# Generated by Django 6.0 on 2025-12-08 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicaoBruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('flag_consistencia', models.CharField(choices=[('OK', 'Ok'), ('SUSPEITO', 'Suspeito'), ('ERRO', 'Erro')], default='OK', max_length=20)),
                ('hash_arquivo', models.CharField(db_index=True, max_length=32)),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='stations.estacao')),
            ],
        ),
    ]
